apiVersion: v1
kind: Template
metadata:
  name: sa-template
  annotations:
    openshift.io/display-name: Service Acount Template
    description: Template to create a service account
objects:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    name: signature-viewer
  rules:
  - apiGroups:
    - image.openshift.io
    - ""
    attributeRestrictions: null
    resources:
    - imagestreamimages
    verbs:
    - get
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${SERVICE_ACCOUNT_NAME}"
    namespace: "${NAMESPACE}"
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: imagemanager-cluster-admin
  roleRef:
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    name: "${SERVICE_ACCOUNT_NAME}"
    namespace: "${NAMESPACE}"
parameters:
- name: SERVICE_ACCOUNT_NAME
  displayName: Service Account Name
  description: Name of the service account to Create
  value: imagemanager
  required: true
- name: NAMESPACE
  displayName: Namespace
  description: Namespace Containing Resources
  value: image-signer
  required: true