---

gpg_core_files_dir: "{{ playbook_dir }}/gpg_remote/gpg_config"
gpg_core_files_remote_dir: "~/.gpg-openshift"
gpg_publickey_file: "openshift@example.com"
openshift_signer_project_name: image-signer
openshift_signer_project_display_name: Image Signer
openshift_signer_node_label: "image_signer=true"
openshift_signer_node_taint: "image_signer=true:NoExecute"
openshift_signer_gpg_secret_name: gpg
openshift_signer_sa_name: imagemanager
openshift_sign_pod_template_name: sign-image-pod-template

image_signer_hostgroup: image_signers

signature_viewer_role: signature-viewer

tmp_default_project_template: /tmp/ocp-default-project-template.yml

openshift_configs_dest_dir: "~/ocp-configs"
openshift_base_scan_template: image-sign-scan-base.yml
openshift_policy_template: policies-template.yml
openshift_sign_image_template: sign-image-template.yml
openshift_sign_image_pod_template: sign-image-pod-template.yml
openshift_scan_image_pod_template: scan-image-pod-template.yml
openshift_event_controller_template: event-controller-template.yml

openshift_configs:
  - "{{ role_path }}/../../../policy/{{ openshift_policy_template }}"
  - "{{ role_path }}/../../../image-sign-scan-base/{{ openshift_base_scan_template }}"
  - "{{ role_path }}/../../../sign-image/{{ openshift_sign_image_template }}"
  - "{{ role_path }}/../../../image-scanning/{{ openshift_scan_image_pod_template }}"
  - "{{ role_path }}/../../../sign-image/{{ openshift_sign_image_pod_template }}"
  - "{{ role_path }}/../../../event-controller/{{ openshift_event_controller_template }}"

deploy_eventcontroller: False
